name       : sox
version    : 14.4.2
release    : 2
source     :
    - https://superb-sea2.dl.sourceforge.net/project/sox/sox/14.4.2/sox-14.4.2.tar.bz2 : 81a6956d4330e75b5827316e44ae381e6f1e8928003c6aa45896da9041ea149c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : multimedia.audio
summary    : SoX (Sound eXchange) is the Swiss Army knife of sound processing tools
description: |
    SoX (Sound eXchange) is the Swiss Army knife of sound processing tools: it can convert sound files between many different file formats & audio devices, and can apply many sound effects & transformations, as well as doing basic analysis and providing input to more capable analysis and plotting tools.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(ao)
    - pkgconfig(flac)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(id3tag)
    - pkgconfig(opusfile)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - lame-devel
    - libmad-devel
setup      : |
    %configure --with-distro="Solus" --disable-static
build      : |
    %make
install    : |
    %make_install
